# Generated by Django 2.1.7 on 2019-03-11 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdataxs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smdataxs',
            new_name='Smdatax',
        ),
    ]
