# Generated by Django 2.1.7 on 2019-03-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_height', models.TextField()),
                ('block_hash', models.TextField()),
                ('timestamp', models.TextField()),
            ],
        ),
    ]
