# Generated by Django 2.1.7 on 2019-03-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='BlockModel',
        ),
    ]
